version: "3.9"

services:
  github-runner:
    build: .
    container_name: github-runner
    restart: always
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
